### PR TITLE
React app

### PR DESCRIPTION
**Pull request by innocentmasuki**
Added search and Fixures

### CODE REVIEW

**Comment by jaiwanth-v** [comment]
What is the tokens field in the bets page?

image

**Review by jaiwanth-v — CHANGES_REQUESTED** [review]
Search is very well done in my opinion. My only nitpick is that the icons in the sidebar are not aligned and the previous comment. Could you take a look?
image

Rest is good.

**Comment by innocentmasuki** [comment]
> Search is very well done in my opinion. My only nitpick is that the icons in the sidebar are not aligned and the previous comment. Could you take a look? image
> 
> Rest is good.

About this, I didn't consider much the UI on the desktop because they don't want it, but I will surely make that correct

**Comment by innocentmasuki** [comment]
> What is the tokens field in the bets page?
> 
> image

I really don't know I think it is a feature needed in future. I was working on the Firebase Auth now we can deal with the chats, bets, notifications and edit profile

**Comment by jaiwanth-v** [comment]
> > Search is very well done in my opinion. My only nitpick is that the icons in the sidebar are not aligned and the previous comment. Could you take a look? image
> > Rest is good.
> 
> About this, I didn't consider much the UI on the desktop because they don't want it, but I will surely make that correct

Sounds good, will you do it in this PR?

**Comment by jaiwanth-v** [comment]
image
Firebase gives an error on the deployment. Would it work fine on ozare-final domain?

**Comment by innocentmasuki** [comment]
> > > Search is very well done in my opinion. My only nitpick is that the icons in the sidebar are not aligned and the previous comment. Could you take a look? image
> > > Rest is good.
> > 
> > 
> > About this, I didn't consider much the UI on the desktop because they don't want it, but I will surely make that correct
> 
> Sounds good, will you do it in this PR?

I have just fixed and pushed

**Comment by innocentmasuki** [comment]
> image Firebase gives an error on the deployment. Would it work fine on ozare-final domain?

I don't think so, I just picked the configs from the last project i think that will need to be fixed on firebase side for us to get new configs for the new site

**Comment by jaiwanth-v** [comment]
Got it

**Pull request merged**
